name: build
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org' # Can I bake this into package.json?
        run: |
          npm install
          npm run build --if-present
          # npm test
      - name: Upload bundled extension
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist